package core

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ReplyToInitiator) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	z.CalibratedExpiration, err = dc.ReadTime()
	if err != nil {
		err = msgp.WrapError(err, "CalibratedExpiration")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ReplyToInitiator) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	err = en.WriteTime(z.CalibratedExpiration)
	if err != nil {
		err = msgp.WrapError(err, "CalibratedExpiration")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ReplyToInitiator) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	o = msgp.AppendTime(o, z.CalibratedExpiration)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReplyToInitiator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	z.CalibratedExpiration, bts, err = msgp.ReadTimeBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "CalibratedExpiration")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ReplyToInitiator) Msgsize() (s int) {
	s = 1 + msgp.TimeSize
	return
}
