// Code generated by "stringer -type=AuthLevel"; DO NOT EDIT.

package sec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequireNoAuth-1]
	_ = x[AuthWhatever-2]
	_ = x[RequireAuth-3]
}

const _AuthLevel_name = "RequireNoAuthAuthWhateverRequireAuth"

var _AuthLevel_index = [...]uint8{0, 13, 25, 36}

func (i AuthLevel) String() string {
	i -= 1
	if i >= AuthLevel(len(_AuthLevel_index)-1) {
		return "AuthLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AuthLevel_name[_AuthLevel_index[i]:_AuthLevel_index[i+1]]
}
