// Code generated by "stringer -type=SecLevel"; DO NOT EDIT.

package sec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequireCleartext-1]
	_ = x[SecWhatever-2]
	_ = x[RequireEncrypted-3]
}

const _SecLevel_name = "RequireCleartextSecWhateverRequireEncrypted"

var _SecLevel_index = [...]uint8{0, 16, 27, 43}

func (i SecLevel) String() string {
	i -= 1
	if i >= SecLevel(len(_SecLevel_index)-1) {
		return "SecLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SecLevel_name[_SecLevel_index[i]:_SecLevel_index[i+1]]
}
