package handshake

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *_V1_Payload) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendBytes(o, z.PeerID)
	o = msgp.AppendBytes(o, z.Sig)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *_V1_Payload) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.PeerID, bts, err = msgp.ReadBytesBytes(bts, z.PeerID)
	if err != nil {
		err = msgp.WrapError(err, "PeerID")
		return
	}
	z.Sig, bts, err = msgp.ReadBytesBytes(bts, z.Sig)
	if err != nil {
		err = msgp.WrapError(err, "Sig")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *_V1_Payload) Msgsize() (s int) {
	s = 1 + msgp.BytesPrefixSize + len(z.PeerID) + msgp.BytesPrefixSize + len(z.Sig)
	return
}
